In [127]:
import pandas as pd
from ast import literal_eval as make_tuple
import numpy as np


In [117]:
path = '/home/suraj/Work/llnl/CallFlow/data/processed/osu_bcast_18/ensemble_entire_df.csv'
group_path = '/home/suraj/Work/llnl/CallFlow/data/processed/osu_bcast_18/ensemble_group_df.csv'
datasets = ['osu_bcast.1.18.2019-09-03_10-33-44', 'osu_bcast.1.18.2019-09-03_11-33-15', 'osu_bcast.1.18.2019-09-03_12-29-49']

In [118]:
df = pd.read_csv(path)
group_df = pd.read_csv(group_path)

In [130]:
for path in group_df['group_path'].unique():
    path_list = make_tuple(path)
    print(path_list[0], path_list[1])

<unknown load module>=<partial call paths> Unknown=<unknown file>:0
libmonitor.so.0.0.0=<program root> osu_bcast=main
libmonitor.so.0.0.0=<program root> osu_bcast=main
libmonitor.so.0.0.0=<program root> osu_bcast=main
libmonitor.so.0.0.0=<program root> osu_bcast=main
libmonitor.so.0.0.0=<program root> osu_bcast=main
libmonitor.so.0.0.0=<program root> osu_bcast=main
libmonitor.so.0.0.0=<program root> osu_bcast=main
libmonitor.so.0.0.0=<program root> osu_bcast=main
libmonitor.so.0.0.0=<program root> osu_bcast=main
libmonitor.so.0.0.0=<program root> osu_bcast=main
libmonitor.so.0.0.0=<program root> osu_bcast=main
libmonitor.so.0.0.0=<program root> osu_bcast=main
libmonitor.so.0.0.0=<program root> osu_bcast=main
libmonitor.so.0.0.0=<program root> osu_bcast=main
libmonitor.so.0.0.0=<program root> osu_bcast=main
libmonitor.so.0.0.0=<program root> osu_bcast=main
libmonitor.so.0.0.0=<program root> osu_bcast=main
libmonitor.so.0.0.0=<program root> osu_bcast=main
libmonitor.so.0.0.0=<program roo

In [49]:
def inclusive_time_by_module(df):
    for dataset in datasets:
        print(dataset)
        dataset_df = df.loc[df['dataset'] == dataset]
        modules = dataset_df['module'].unique()
        for module in modules:
            module_df = dataset_df.loc[dataset_df['module'] == module]['time (inc)'].max()
            print(module, module_df)
        print('======================')    

In [50]:
inclusive_time_by_module(df)

osu_bcast.1.18.2019-09-03_10-33-44
<unknown load module> 12918.0
Unknown 281594.0
libmonitor.so.0.0.0 1147289.0
osu_bcast 1147289.0
libmpi.so.12.1.1 1007467.0
libpsm_infinipath.so.1.16 1006585.0
libc-2.17.so 125821.0
libpmi2.so.0.0.0 5998.0
libpthread-2.17.so 5998.0
libinfinipath.so.4.0 5987.0
osu_bcast.1.18.2019-09-03_11-33-15
<unknown load module> 6987.0
Unknown 287599.0
libmonitor.so.0.0.0 1139918.0
osu_bcast 1139918.0
libc-2.17.so 107864.0
libmpi.so.12.1.1 1006561.0
libpsm_infinipath.so.1.16 1006535.0
libinfinipath.so.4.0 5987.0
libpthread-2.17.so 5987.0
osu_bcast.1.18.2019-09-03_12-29-49
<unknown load module> 5948.0
Unknown 305470.0
libmonitor.so.0.0.0 1140997.0
osu_bcast 1140997.0
libmpi.so.12.1.1 1007833.0
libpsm_infinipath.so.1.16 1007045.0
libc-2.17.so 107860.0
libinfinipath.so.4.0 5992.0


In [45]:
def exclusive_time_by_module(df):
    for dataset in datasets:
        print(dataset)
        dataset_df = df.loc[df['dataset'] == dataset]
        modules = dataset_df['module'].unique()
        for module in modules:
            module_df = dataset_df.loc[dataset_df['module'] == module]['time']
            print(module, module_df.sum())
        print('======================')

In [46]:
exclusive_time_by_module(df)

osu_bcast.1.18.2019-09-03_10-33-44
<unknown load module> 0.0
Unknown 20629541.0
libmonitor.so.0.0.0 0.0
osu_bcast 0.0
libmpi.so.12.1.1 0.0
libpsm_infinipath.so.1.16 0.0
libc-2.17.so 0.0
libpmi2.so.0.0.0 0.0
libpthread-2.17.so 0.0
libinfinipath.so.4.0 0.0
osu_bcast.1.18.2019-09-03_11-33-15
<unknown load module> 0.0
Unknown 20502779.0
libmonitor.so.0.0.0 0.0
osu_bcast 0.0
libc-2.17.so 0.0
libmpi.so.12.1.1 0.0
libpsm_infinipath.so.1.16 0.0
libinfinipath.so.4.0 0.0
libpthread-2.17.so 0.0
osu_bcast.1.18.2019-09-03_12-29-49
<unknown load module> 0.0
Unknown 20511173.0
libmonitor.so.0.0.0 0.0
osu_bcast 0.0
libmpi.so.12.1.1 0.0
libpsm_infinipath.so.1.16 0.0
libc-2.17.so 0.0
libinfinipath.so.4.0 0.0


In [32]:
def exclusive_time_by_callsite_and_module(df, dataset):
    df = df.loc[df['dataset'] == dataset]
    callsites = df.loc[df['time'] > 0]['name'].unique()
    sum_of_time = 0
    for callsite in callsites:
        callsite_df = df.loc[df['name'] == callsite]
        max_time = callsite_df['time'].max()
        module = callsite_df['module'].unique()
        sum_of_time += max_time
        print(callsite, module, max_time)
    print(sum_of_time)

In [33]:
for dataset in datasets:
    print("Dataset: ", dataset)
    exclusive_time_by_callsite_and_module(df, dataset)
    print("====================")

Dataset:  osu_bcast.1.18.2019-09-03_10-33-44
<unknown file>:0 ['Unknown'] 12918.0
ch3_shmem_coll.c:90 ['Unknown'] 5945.0
<unknown file> [libpsm_infinipath.so.1.16]:0 ['Unknown'] 281594.0
syslog.c:244 ['Unknown'] 7131.0
getopt.c:716 ['Unknown'] 125821.0
syscall-template.S:81 ['Unknown'] 5998.0
bcast_osu.c:2553 ['Unknown'] 5992.0
bcast_osu.c:2567 ['Unknown'] 5946.0
<unknown file> [libmpi.so.12.1.1]:0 ['Unknown'] 5989.0
bcast_osu.c:1960 ['Unknown'] 5990.0
malloc.c:4596 ['Unknown'] 5972.0
<unknown file> [osu_bcast]:0 ['Unknown'] 84817.0
ch3_shmem_coll.c:3613 ['Unknown'] 5988.0
<unknown file> [libpsm_infinipath.so.1.16]:1163 ['Unknown'] 5803.0
<unknown file> [osu_bcast]:3806 ['Unknown'] 30484.0
<unknown file> [osu_bcast]:3807 ['Unknown'] 5967.0
<unknown file> [osu_bcast]:3808 ['Unknown'] 11892.0
ch3_shmem_coll.c:3623 ['Unknown'] 5987.0
ch3_shmem_coll.c:3624 ['Unknown'] 5988.0
ch3_shmem_coll.c:3625 ['Unknown'] 5991.0
psm_queue.c:267 ['Unknown'] 5990.0
psm_queue.c:274 ['Unknown'] 6925.0
psm_q

In [79]:
import json

mean_df = df.groupby(['dataset','module', 'name'])
print(mean_df.groups.keys())
time_mean = mean_df['time', 'time (inc)'].mean()
print(time_mean.columns)

dict_keys([('osu_bcast.1.18.2019-09-03_10-33-44', '<unknown load module>', '<partial call paths>'), ('osu_bcast.1.18.2019-09-03_10-33-44', '<unknown load module>', '<unknown procedure>'), ('osu_bcast.1.18.2019-09-03_10-33-44', 'Unknown', '<unknown file> [libinfinipath.so.4.0]:0'), ('osu_bcast.1.18.2019-09-03_10-33-44', 'Unknown', '<unknown file> [libmonitor.so.0.0.0]:0'), ('osu_bcast.1.18.2019-09-03_10-33-44', 'Unknown', '<unknown file> [libmpi.so.12.1.1]:0'), ('osu_bcast.1.18.2019-09-03_10-33-44', 'Unknown', '<unknown file> [libmpi.so.12.1.1]:1738'), ('osu_bcast.1.18.2019-09-03_10-33-44', 'Unknown', '<unknown file> [libpsm_infinipath.so.1.16]:0'), ('osu_bcast.1.18.2019-09-03_10-33-44', 'Unknown', '<unknown file> [libpsm_infinipath.so.1.16]:1163'), ('osu_bcast.1.18.2019-09-03_10-33-44', 'Unknown', '<unknown file> [libpsm_infinipath.so.1.16]:234'), ('osu_bcast.1.18.2019-09-03_10-33-44', 'Unknown', '<unknown file> [libpsm_infinipath.so.1.16]:247'), ('osu_bcast.1.18.2019-09-03_10-33-44', 

TypeError: keys must be str, int, float, bool or None, not tuple

In [82]:
print(mean_df.get_group(('osu_bcast.1.18.2019-09-03_10-33-44', '<unknown load module>', '<partial call paths>')))


       Unnamed: 0                                               node  rank  \
16038           0  {'name': '<partial call paths>', 'type': 'func...     0   
16039           1  {'name': '<partial call paths>', 'type': 'func...     1   
16040           2  {'name': '<partial call paths>', 'type': 'func...     2   
16041           3  {'name': '<partial call paths>', 'type': 'func...     3   
16042           4  {'name': '<partial call paths>', 'type': 'func...     4   
16043           5  {'name': '<partial call paths>', 'type': 'func...     5   
16044           6  {'name': '<partial call paths>', 'type': 'func...     6   
16045           7  {'name': '<partial call paths>', 'type': 'func...     7   
16046           8  {'name': '<partial call paths>', 'type': 'func...     8   
16047           9  {'name': '<partial call paths>', 'type': 'func...     9   
16048          10  {'name': '<partial call paths>', 'type': 'func...    10   
16049          11  {'name': '<partial call paths>', 'type': 'fun

In [ ]:
modules = df['module'].unique()
for module in modules:
    mean_df.loc[mean_df['module'] == module]['time'].sum()

In [86]:
module_name_group_df = df.groupby(['module', 'name'])
module_name_times = module_name_group_df[['time', 'time (inc)']].max().to_dict()
print(module_name_times)

{'time': {('<unknown load module>', '<partial call paths>'): 0.0, ('<unknown load module>', '<unknown procedure>'): 0.0, ('Unknown', '<unknown file> [libinfinipath.so.4.0]:0'): 5992.0, ('Unknown', '<unknown file> [libmonitor.so.0.0.0]:0'): 0.0, ('Unknown', '<unknown file> [libmpi.so.12.1.1]:0'): 6986.0, ('Unknown', '<unknown file> [libmpi.so.12.1.1]:1193'): 8174.0, ('Unknown', '<unknown file> [libmpi.so.12.1.1]:1738'): 5861.0, ('Unknown', '<unknown file> [libmpi.so.12.1.1]:1802'): 25925.0, ('Unknown', '<unknown file> [libmpi.so.12.1.1]:1807'): 5990.0, ('Unknown', '<unknown file> [libmpi.so.12.1.1]:1810'): 5988.0, ('Unknown', '<unknown file> [libmpi.so.12.1.1]:1835'): 8113.0, ('Unknown', '<unknown file> [libmpi.so.12.1.1]:1840'): 5871.0, ('Unknown', '<unknown file> [libmpi.so.12.1.1]:2509'): 8176.0, ('Unknown', '<unknown file> [libmpi.so.12.1.1]:2594'): 5989.0, ('Unknown', '<unknown file> [libmpi.so.12.1.1]:2667'): 5989.0, ('Unknown', '<unknown file> [libmpi.so.12.1.1]:2808'): 5989.0, (

In [106]:
def node_time(module):
    exc_time_sum = 0
    inc_time_max = 0
    module_df = df.loc[df['module'] == module]
    callsites = module_df['name'].unique()
    for callsite in callsites:
        callsite_df = module_name_group_df.get_group((module, callsite))
        max_inc_time = callsite_df['time (inc)'].max()
        inc_time_max = max(inc_time_max, max_inc_time)
        max_exc_time = callsite_df['time'].max()
        exc_time_sum += max_exc_time
#         print(callsite, max_exc_time, max_inc_time)
    return {
        'Exclusive_sum': exc_time_sum,
        'Inclusive_max': inc_time_max
    }

In [108]:
for module in modules:
    time_info = node_time(module)
    module_value = max(time_info['Exclusive_sum'], time_info['Inclusive_max'])
    print(module, module_value)

<unknown load module> 12918.0
Unknown 1069459.0
libmonitor.so.0.0.0 1147289.0
osu_bcast 1147289.0
libc-2.17.so 125821.0
libmpi.so.12.1.1 1007833.0
libpsm_infinipath.so.1.16 1007045.0
libinfinipath.so.4.0 5992.0
libpthread-2.17.so 5998.0
libpmi2.so.0.0.0 5998.0


In [111]:
unique_callsites_in_module = df.groupby(['module'])['name'].unique()
print(unique_callsites_in_module)

module
<unknown load module>              [<partial call paths>, <unknown procedure>]
Unknown                      [<unknown file>:0, syslog.c:244, malloc.c:3986...
libc-2.17.so                 [1087:__GI___vsyslog_chk, _int_free, _getopt_i...
libinfinipath.so.4.0         [<unknown procedure> 0xa128 [libinfinipath.so....
libmonitor.so.0.0.0          [<program root>, 119:MPI_Finalize, 36:MPI_Init...
libmpi.so.12.1.1             [PMPI_Finalize, 296:MPID_Finalize, 174:psm_dof...
libpmi2.so.0.0.0                           [109:snprintf, 64:PMIi_ReadCommand]
libpsm_infinipath.so.1.16    [35:<unknown procedure> 0x1e450 [libpsm_infini...
libpthread-2.17.so           [__pthread_cond_broadcast_2_0, 1431:__write_no...
osu_bcast                    [main, 117:free_buffer, 3820:__intel_ssse3_rep...
Name: name, dtype: object


In [149]:
auxiliary_ensemble_df = df.groupby(['module', 'name'])
auxiliary_target_df = df.groupby(['dataset','module', 'name'])

In [150]:
for name, group in auxiliary_target_df:
    print(name)
    print(np.quantile(np.array(group['time (inc)'].tolist()), [0, 0.25, 0.5, 0.75, 1.0]))

('osu_bcast.1.18.2019-09-03_10-33-44', '<unknown load module>', '<partial call paths>')
[    0.     0.     0.     0. 12918.]
('osu_bcast.1.18.2019-09-03_10-33-44', '<unknown load module>', '<unknown procedure>')
[    0.     0.     0.     0. 12918.]
('osu_bcast.1.18.2019-09-03_10-33-44', 'Unknown', '<unknown file> [libinfinipath.so.4.0]:0')
[   0.    0.    0.    0. 5987.]
('osu_bcast.1.18.2019-09-03_10-33-44', 'Unknown', '<unknown file> [libmonitor.so.0.0.0]:0')
[0. 0. 0. 0. 0.]
('osu_bcast.1.18.2019-09-03_10-33-44', 'Unknown', '<unknown file> [libmpi.so.12.1.1]:0')
[   0.    0.    0.    0. 5989.]
('osu_bcast.1.18.2019-09-03_10-33-44', 'Unknown', '<unknown file> [libmpi.so.12.1.1]:1738')
[   0.    0.    0.    0. 5861.]
('osu_bcast.1.18.2019-09-03_10-33-44', 'Unknown', '<unknown file> [libpsm_infinipath.so.1.16]:0')
[     0.      0.      0.   5992. 281594.]
('osu_bcast.1.18.2019-09-03_10-33-44', 'Unknown', '<unknown file> [libpsm_infinipath.so.1.16]:1163')
[   0.    0.    0.    0. 5803.]

[    0.       0.    5991.    7439.75 23969.  ]
('osu_bcast.1.18.2019-09-03_11-33-15', 'libpsm_infinipath.so.1.16', '<unknown procedure> 0x1c096 [libpsm_infinipath.so.1.16]')
[    0.    5990.75  5992.    5993.   17975.  ]
('osu_bcast.1.18.2019-09-03_11-33-15', 'libpsm_infinipath.so.1.16', '<unknown procedure> 0x1c09c [libpsm_infinipath.so.1.16]')
[   0.    0.    0.    0. 5992.]
('osu_bcast.1.18.2019-09-03_11-33-15', 'libpsm_infinipath.so.1.16', '<unknown procedure> 0x1c0a3 [libpsm_infinipath.so.1.16]')
[    0.    5991.75 11981.   13483.25 29961.  ]
('osu_bcast.1.18.2019-09-03_11-33-15', 'libpsm_infinipath.so.1.16', '<unknown procedure> 0x1da64 [libpsm_infinipath.so.1.16]')
[   0.    0.    0.    0. 5987.]
('osu_bcast.1.18.2019-09-03_11-33-15', 'libpsm_infinipath.so.1.16', '<unknown procedure> 0x1e82f [libpsm_infinipath.so.1.16]')
[   0.    0.    0.    0. 6003.]
('osu_bcast.1.18.2019-09-03_11-33-15', 'libpsm_infinipath.so.1.16', '<unknown procedure> 0x20e9e [libpsm_infinipath.so.1.16]')
[

In [151]:
for name, group in auxiliary_ensemble_df:
    print(name)
    print(np.quantile(np.array(group['time (inc)'].tolist()), [0, 0.25, 0.5, 0.75, 1.0]))

('<unknown load module>', '<partial call paths>')
[    0.     0.     0.     0. 12918.]
('<unknown load module>', '<unknown procedure>')
[    0.     0.     0.     0. 12918.]
('Unknown', '<unknown file> [libinfinipath.so.4.0]:0')
[   0.    0.    0.    0. 5992.]
('Unknown', '<unknown file> [libmonitor.so.0.0.0]:0')
[0. 0. 0. 0. 0.]
('Unknown', '<unknown file> [libmpi.so.12.1.1]:0')
[   0.    0.    0.    0. 6986.]
('Unknown', '<unknown file> [libmpi.so.12.1.1]:1193')
[   0.    0.    0.    0. 8174.]
('Unknown', '<unknown file> [libmpi.so.12.1.1]:1738')
[   0.    0.    0.    0. 5861.]
('Unknown', '<unknown file> [libmpi.so.12.1.1]:1802')
[    0.   5735.5  5850.5  5989.  25925. ]
('Unknown', '<unknown file> [libmpi.so.12.1.1]:1807')
[   0.    0.    0.    0. 5990.]
('Unknown', '<unknown file> [libmpi.so.12.1.1]:1810')
[   0.    0.    0.    0. 5988.]
('Unknown', '<unknown file> [libmpi.so.12.1.1]:1835')
[   0.    0.    0.    0. 8113.]
('Unknown', '<unknown file> [libmpi.so.12.1.1]:1840')
[   0.