In [1]:
from hatchet import *
import pandas as pd
import numpy as np

In [16]:
data_path = '/Users/jarus/ucd/Research/Visualisation/projects/CallFlow/data/hpctoolkit-lulesh-2'
# data_path = '/home/vidi/Work/llnl/CallFlow/data/kripke/mvapich2'

In [17]:
gf = GraphFrame()
gf.from_hpctoolkit(data_path)

[4612081.       0. 4612081. ...    5996.   59960.   59960.]
[4616159.       0. 4616159. ...   11993.   17988.   17988.]
[4615343.       0. 4615343. ...   41976.   47962.   47962.]
[4620810.       0. 4620810. ...    5997.   35979.   35979.]
[4613806.       0. 4613806. ...   11994.   95942.   95942.]
[4615792.       0. 4615792. ...       0.   23984.   23984.]
[4614665.       0. 4614665. ...       0.   35969.   35969.]
[4614204.       0. 4614204. ...   17988.   17986.   17986.]


In [18]:
df = gf.dataframe
graph = gf.graph

In [31]:
print(df['module'].unique())

['/collab/usr/global/tools/hpctoolkit/chaos_5_x86_64_ib/hpctoolkit-2017-03-16/lib/hpctoolkit/ext-libs/libmonitor.so.0.0.0'
 '/g/g92/bhatele1/llnl/hpctoolkit/lulesh/lulesh2.0'
 '/usr/local/tools/mvapich2-intel-debug-2.2/lib/libmpi.so.12.0.5'
 '/usr/lib64/libpsm_infinipath.so.1.14' None
 '/usr/lib64/libinfinipath.so.4.0' '/lib64/libc-2.12.so']


In [35]:
a = df.loc[df['name'] == '<program root>']['time (inc)'].mean()
b = df.loc[df['name']== '2774:LagrangeLeapFrog(Domain&)']['time (inc)'].mean()
c = df.loc[df['module'] == "/usr/local/tools/mvapich2-intel-debug-2.2/lib/libmpi.so.12.0.5"]['time (inc)'].mean()
print(a, b, c)
print(b/a, c/a)

4615357.5 3138549.375 123637.9517857143
0.68002302638528 0.02678838026863884


In [13]:
print(df.info())
print(df.groupby(['module']).mean())

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 10312 entries, (<program root>, 0) to (interp.c:0, 7)
Data columns (total 10 columns):
time (inc)    10312 non-null float64
time          10312 non-null float64
nid           10312 non-null int64
rank          10312 non-null int64
file          10312 non-null object
line          10312 non-null object
module        2864 non-null object
name          10312 non-null object
node          10312 non-null object
type          10312 non-null object
dtypes: float64(2), int64(2), object(6)
memory usage: 846.1+ KB
None
                                                      time (inc)         time  \
module                                                                          
/collab/usr/global/tools/hpctoolkit/chaos_5_x86...  1.124668e+06     0.000000   
/g/g92/bhatele1/llnl/hpctoolkit/lulesh/lulesh2.0    1.101783e+05  8760.722426   
/lib64/libc-2.12.so                                 7.663875e+03     0.000000   
/usr/lib64/libinfinipath.so.4.

In [15]:
# None modules:
print(df.loc[df['module'] == None])

Empty DataFrame
Columns: [time (inc), time, nid, rank, file, line, module, name, node, type]
Index: []
